apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: flux
  name: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: flux
  name: flux
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: flux
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  clusterIP: None
  ports:
  - name: memcached
    port: 11211
  selector:
    name: memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 3
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io.port: "3031"
      labels:
        name: flux
    spec:
      containers:
      - args:
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-url=git@github.com:replicatedhq/repldev-gitops.git
        - --git-branch=master
        - --listen-metrics=:3031
        image: quay.io/weaveworks/flux:1.8.1
        imagePullPolicy: IfNotPresent
        name: flux
        ports:
        - containerPort: 3030
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/fluxd/ssh
          name: git-key
          readOnly: true
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          defaultMode: 256
          secretName: flux-git-deploy
      - emptyDir:
          medium: Memory
        name: git-keygen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - args:
        - -m 64
        - -p 11211
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: clients
